SELECT [pc_company_amp_id]
      ,[performance_commitment_id]
      ,[pc_name]
      ,[water_company_id]
      ,[unique_id]
      ,[outcome]
      ,[PC_ref]
      ,[common_comparable_bespoke_performance_commitment]
      ,[annex]
      ,[direction_of_improving_performance]
      ,[drinking_water_quality_compliance]
      ,[water_quality_contacts]
      ,[supply_interruptions_3_hours]
      ,[pollution_incidents_cat_3]
      ,[internal_sewer_flooding]
      ,[special_cost_factor]
      ,[scheme_specific_factor]
      ,[asset_health]
      ,[nep]
      ,[AIM]
      ,[customers_relative_priority]
      ,[no_of_sub_measures]
      ,[standard_odi_cal]
      ,[standard_odi_operand]
      ,[standard_odi_operand_note]
      ,[UnderP_payment1_incentive rate (GBPm)]
      ,[UnderP_payment2_incentive rate (GBPm)]
      ,[UnderP_payment3_incentive rate (GBPm)]
      ,[UnderP_payment4_incentive rate (GBPm)]
      ,[OutP_payment1_incentive rate (GBPm)]
      ,[OutP_payment2_incentive rate (GBPm)]
      ,[Underperformance payment incentive rates -£m (2017-18 CPIH deflated) Standard underperformance payment 1 (tier 2)]
      ,[Underperformance payment incentive rates -£m (2017-18 CPIH deflated) Standard underperformance payment 2 (tier 1)]
      ,[Underperformance payment incentive rates -£m (2017-18 CPIH deflated) Standard underperformance payment 3 (tier 3)]
      ,[Underperformance payment incentive rates -£m (2017-18 CPIH deflated) Enhanced underperformance payment]
      ,[Outperformance payment incentive rates £m (2017-18 CPIH deflated) Standard outperformance payment 1 (tier 2)]
      ,[Outperformance payment incentive rates £m (2017-18 CPIH deflated) Standard outperformance payment 2 (tier 1)]
      ,[Outperformance payment incentive rates £m (2017-18 CPIH deflated) Standard outperformance payment 3 (tier 3)]
      ,[Outperformance payment incentive rates £m (2017-18 CPIH deflated) Enhanced outperformance payment]
      ,[water_resources]
      ,[water_network_plus]
      ,[wastewater_network_plus]
      ,[bioresources_sludge]
      ,[residential_retail]
      ,[business_retail]
      ,[direct_procurement_for_customers]
      ,[dummy_control]
  FROM {{ ref('stg_PC_company_amp_union')}}